// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoV5ZRi6jh60-BhhZZHu2NaIyGdWyGOA0',
    appId: '1:174031798705:web:10c2b3eae7cacb39a57d90',
    messagingSenderId: '174031798705',
    projectId: 'ams-student-module',
    authDomain: 'ams-student-module.firebaseapp.com',
    storageBucket: 'ams-student-module.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHVRpVwiK0r1pLlJ7cM763WQsB9hPZeng',
    appId: '1:174031798705:android:3b5a67865c51dfc8a57d90',
    messagingSenderId: '174031798705',
    projectId: 'ams-student-module',
    storageBucket: 'ams-student-module.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN1ctqboMF1tLgxTEo0q7izs9oc8u1jxw',
    appId: '1:174031798705:ios:2fc002c9ab128f7fa57d90',
    messagingSenderId: '174031798705',
    projectId: 'ams-student-module',
    storageBucket: 'ams-student-module.firebasestorage.app',
    iosBundleId: 'com.example.attendanceManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN1ctqboMF1tLgxTEo0q7izs9oc8u1jxw',
    appId: '1:174031798705:ios:2fc002c9ab128f7fa57d90',
    messagingSenderId: '174031798705',
    projectId: 'ams-student-module',
    storageBucket: 'ams-student-module.firebasestorage.app',
    iosBundleId: 'com.example.attendanceManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoV5ZRi6jh60-BhhZZHu2NaIyGdWyGOA0',
    appId: '1:174031798705:web:b2186bc9c802b6e0a57d90',
    messagingSenderId: '174031798705',
    projectId: 'ams-student-module',
    authDomain: 'ams-student-module.firebaseapp.com',
    storageBucket: 'ams-student-module.firebasestorage.app',
  );
}
